update

diff --git a/.bin/d6 b/.bin/d6
--- a/.bin/d6
+++ b/.bin/d6
@@ -2,18 +2,17 @@
 
 function help {
 cat <<'EOF'
-usage: d6 <spec> <tool> <format> <dsn-token> [options]
+usage: d6 <spec> <tool> <dsn-token> [options]
    or: d6 --help
 
 Arguments:
-  <spec>        mongo | { redshift | postgres } | heroku | mssql | redis | cassandra | bypass
-  <tool>        shell | uri
-  <format>      Use case:               Description:
-    -           redshift shell -        Default output format
-    csv         redshift shell csv      Hints the tool to output the data in CSV format
+  <spec>        mongo | { redshift | postgres } | mssql | redis | cassandra | astra | bypass
+  <tool>        shell | uri | unload | load
   <dsn-token>   token from DSN conf
 
 Options (DSN overrides):
+  --format                Format in which the output is presented
+
   --host                  overrides 'host'
   --port                  overrides 'port'
   --database              overrides 'database'
@@ -59,70 +58,12 @@ SPEC="$1"; shift
 # shell - runs a cli shell/tool for the dbms specified by $SPEC
 # uri - outputs connection strings in a format specified by $FORMAT
 TOOL="$1"; shift
-# format of the output (processing details)
-FORMAT="$1"; shift
+FORMAT=''
 # name of the token to read the connection attributes from
 NAME="$1"; shift
 
-# validate all positional arguments
-case $SPEC in
-  "bypass")
-    case "$FORMAT" in
-      - | -- | default) ;;
-      *) error "'$FORMAT' output format is not supported"; exit 1
-    esac
-    ;;
-  "mongo")
-    case "$FORMAT" in
-      - | -- | default) ;;
-      *) error "'$FORMAT' output format is not supported"; exit 1
-    esac
-    ;;
-  "redshift" | "postgres")
-    case "$FORMAT" in
-      csv | psycopg | - | -- | default) ;;
-      *) error "'$FORMAT' format is not supported"; exit 1
-    esac
-    ;;
-  "heroku")
-    case "$FORMAT" in
-      - | -- | default) ;;
-      *) error "'$FORMAT' format is not supported"; exit 1
-    esac
-    ;;
-  "mssql")
-    ;;
-  "redis")
-    case "$FORMAT" in
-      - | -- | default) ;;
-      *) error "'$FORMAT' format is not supported"; exit 1
-    esac
-    ;;
-  "cassandra")
-    case "$FORMAT" in
-      - | -- | default) ;;
-      *) error "'$FORMAT' format is not supported"; exit 1
-    esac
-    ;;
-  *) error "'$SPEC' spec is not supported"; exit 1
-esac
-case $TOOL in
-  "shell" | "uri") ;;
-  *) error "'$TOOL' is not a valid argument"; exit 1
-esac
-
-_scope="${SPEC^^}"
-
-# read database connection attributes into a map
-declare -A _map
-for FIELD in host port database username password app connect-timeout secure-bundle
-do
-  _key="$(echo "$FIELD" | sed 's/-/_/g')"
-  _map[$_key]="$(yq e ".$_scope.$NAME.$FIELD" "$_dsn_conf_path")"
-done
-
 # read all the optional arguments
-ARGS=`getopt --name 'database-tool' --options 'asc' --longoptions database: -- "$@"`
+ARGS=`getopt --name 'database-tool' --options 'asc' --longoptions database,format: -- "$@"`
 eval set -- "$ARGS"
 
 # parameters can be overridden
@@ -131,13 +72,80 @@ do
   case "$1" in
     --database)
         case "$2" in
-          "") shift 2 ;;
+          '') shift 2 ;;
           *) _map[database]="$2"; shift 2 ;;
         esac ;;
+    --format)
+        case "$2" in
+          '') shift 2 ;;
+          *) FORMAT="$2"; shift 2 ;;
+        esac ;;
     --) shift; break ;;
-    *) echo "error parsing args"; exit 1
+    *) echo 'error parsing args'; exit 1
   esac
 done
+
+# validate all positional arguments
+case $SPEC in
+  'bypass')
+    case "$FORMAT" in
+      '' | - | -- | default) ;;
+      *) error "'$FORMAT' output format is not supported"; exit 1
+    esac
+    ;;
+  'mongo')
+    case "$FORMAT" in
+      '' | - | -- | default) ;;
+      *) error "'$FORMAT' output format is not supported"; exit 1
+    esac
+    ;;
+  'redshift' | 'postgres')
+    case "$FORMAT" in
+      '' | csv | psycopg | - | -- | default) ;;
+      *) error "'$FORMAT' format is not supported"; exit 1
+    esac
+    ;;
+  'mssql')
+    ;;
+  'redis')
+    case "$FORMAT" in
+      '' | - | -- | default) ;;
+      *) error "'$FORMAT' format is not supported"; exit 1
+    esac
+    ;;
+  'cassandra' | 'astra')
+    case "$FORMAT" in
+      '' | json | csv | - | -- | default) ;;
+      *) error "'$FORMAT' format is not supported"; exit 1
+    esac
+    ;;
+  *) error "'$SPEC' spec is not supported"; exit 1
+esac
+
+case $TOOL in
+  'shell' | 'uri' | 'unload' | 'load') ;;
+  *) error "'$TOOL' is not a valid argument"; exit 1
+esac
+
+_scope="$SPEC"
+
+# read database connection attributes into a map
+declare -A _map
+for FIELD in host port database username password passkey app connect-timeout secure-bundle
+do
+  _key="$(echo "$FIELD" | sed 's/-/_/g')"
+  _map[$_key]="$(yq e ".$_scope.$NAME.$FIELD" "$_dsn_conf_path")"
+done
+
+# use keyring if passkey is specified
+if [[ "${_map[username]}" == 'null' ]]
+then
+  _map[username]="$(secret-tool lookup "d6:$_scope.$NAME" 'username')"
+fi
+if [[ "${_map[password]}" == 'null' ]]
+then
+  _map[password]="$(secret-tool lookup "d6:$_scope.$NAME" 'password')"
+fi
 
 # make sure there is no 'null' value returned by `yq`
 # in case the attribute could not be found
@@ -173,10 +181,10 @@ case $SPEC in
     esac
     ;;
 
-  "redshift" | "postgres")
+  'redshift' | 'postgres')
 
     case $TOOL in
-      "shell")
+      'shell')
         _psql_params=
         _csv_params='--no-align --field-separator "," --pset footer'
 
@@ -187,7 +195,7 @@ case $SPEC in
 
         PGPASSWORD="${_map[password]}" psql ${_psql_params} -h ${_map[host]} -U ${_map[username]} -d ${_map[database]} -p ${_map[port]} --quiet
         ;;
-      "uri")
+      'uri')
         case "$FORMAT" in
           psycopg)
             echo "host='${_map[host]}' port=${_map[port]} dbname='${_map[database]}' user='${_map[username]}' password='${_map[password]}'"
@@ -199,54 +207,69 @@ case $SPEC in
     esac
     ;;
 
-  "heroku")
-
-    case $TOOL in
-      "shell")
-        _heroku_params=
-
-        case "$FORMAT" in
-          - | -- | default) ;;
-        esac
-        heroku pg:psql ${_map[database]} --app ${_map[app]}
-        ;;
-    esac
-    ;;
-
   "mssql")
 
     case $TOOL in
-      "shell")
+      'shell')
         $(isql '$NAME' '${_map[username]}' '${_map[password]}')
         ;;
-      "uri")
+      'uri')
         error "$SPEC $TOOL not supported" ;;
     esac
     ;;
 
-  "redis")
+  'redis')
 
     case $TOOL in
-      "shell")
+      'shell')
         redis-cli -u "redis://${_map[username]}:${_map[password]}@${_map[host]}:${_map[port]}"
         ;;
-      "uri")
+      'uri')
         error "$SPEC $TOOL not supported" ;;
     esac
     ;;
 
-  "cassandra")
+  'cassandra' | 'astra')
 
     case $TOOL in
-      "shell")
+      'shell')
         if [[ -z "${_map[secure_bundle]}" ]]
         then
-          cqlsh -u "${_map[username]}" -p "${_map[password]}" --connect-timeout="${_map[connect_timeout]:-10}" "${_map[host]}" "${_map[port]}"
+          cqlsh -u "${_map[username]}" -p "${_map[password]}" --connect-timeout="${_map[connect_timeout]:-120}" "${_map[host]}" "${_map[port]}"
         else
-          cqlsh -u "${_map[username]}" -p "${_map[password]}" -b "${_map[secure_bundle]}" --connect-timeout="${_map[connect_timeout]:-10}"
+          cd ~/projects/tools/cqlsh/bin/
+          ./cqlsh -u "${_map[username]}" -p "${_map[password]}" -b "${_map[secure_bundle]}" --connect-timeout="${_map[connect_timeout]:-120}" --request-timeout=12000 --no-color
         fi
         ;;
-      "uri")
+
+      'unload')
+        output_format="${FORMAT:-json}"
+        if [[ -z "$DSBULK_KEYSPACE" ]]
+        then
+          unset lines
+          readarray lines < <(cat -)
+          q=
+          for i in ${!lines[@]}; do
+              q="$q ${lines[i]}"
+          done
+          query=$(echo "$q" | tr '\n' ' ')
+          cd ~/projects/tools/dsbulk-1.8.0/bin/
+          ./dsbulk unload -query "$query" -u "${_map[username]}" -p "${_map[password]}" -b "${_map[secure_bundle]}" --connect-timeout=20 --request-timeout=12000 -c "$output_format"
+        else
+          cd ~/projects/tools/dsbulk-1.8.0/bin/
+          ./dsbulk unload -k "${DSBULK_KEYSPACE}" -t "${DSBULK_TABLE}" -delim '\t' -u "${_map[username]}" -p "${_map[password]}" -b "${_map[secure_bundle]}" --connect-timeout=120 --request-timeout=12000 -c "$output_format"
+        fi
+        ;;
+
+      'load')
+        output_format="${FORMAT:-json}"
+        echo "secure-bundle: ${_map[secure_bundle]}"
+        cd ~/projects/tools/dsbulk-1.8.0/bin/
+        ./dsbulk load -k "${DSBULK_KEYSPACE}" -t "${DSBULK_TABLE}" -delim '\t' -u "${_map[username]}" -p "${_map[password]}" -b "${_map[secure_bundle]}" --connect-timeout=120 --request-timeout=12000 -c "$output_format"
+        # echo "-k ${DSBULK_KEYSPACE} -t ${DSBULK_TABLE} -delim '\t' -u ${_map[username]} -p ${_map[password]} -b ${_map[secure_bundle]} --connect-timeout=20 --request-timeout=6000 -c $output_format"
+        ;;
+
+      'uri')
         error "$SPEC $TOOL not supported" ;;
     esac
     ;;
diff --git a/.bin/nvim-pipe b/.bin/nvim-pipe
--- a/.bin/nvim-pipe
+++ b/.bin/nvim-pipe
@@ -4,16 +4,17 @@ nvimSocketNamePrefix="/tmp/nvimsocket"
 
 NAME="$1"; shift
 
-if [[ "$NAME" == "-" ]]
+if [[ -z "$NAME" ]]
 then
-  NAME="$NVIM_PIPE"
+  >&2 echo 'No target pipe'
+  exit 1
 fi
 
 SERVERNAME="${nvimSocketNamePrefix}-${NAME}"
 
 if [ ! -e "$SERVERNAME" ]
 then
-  echo "File $SERVERNAME does not exit."
+  >&2 echo "File $SERVERNAME does not exist"
   exit 1
 fi
 
@@ -46,7 +47,7 @@ do
       shift
       break ;;
     *)
-      echo "error parsing args"
+      >&2 echo "Error parsing args"
       exit 1 ;;
   esac
 done
