update

diff --git a/.bin/mongo-params b/.bin/mongo-params
--- a/.bin/mongo-params
+++ b/.bin/mongo-params
@@ -1,9 +1,51 @@
 #!/usr/local/bin/bash
 
-declare -A MAP
-
-for FIELD in host port database; do
-  MAP[$FIELD]=$(cat ~/projects/dsn.conf.yaml | yq r - "$1.$FIELD");
+declare -A _map
+for FIELD in host port database
+do
+  _map[$FIELD]=$(cat ~/projects/dsn.conf.yaml | yq r - "$1.$FIELD");
 done
 
-mongo --quiet "mongodb://${MAP[host]}:${MAP[port]}/${MAP[database]}"
+# database parameter can be overridden
+NAME="$1"; shift
+
+ARGS=`getopt --name 'mongo-params' --options 'asc' --longoptions database: -- "$@"`
+eval set -- "$ARGS"
+
+while true
+do
+  case "$1" in
+    --database)
+        case "$2" in
+          "")
+            shift 2 ;;
+          *)
+            _map[database]="$2"
+            shift 2 ;;
+        esac ;;
+    --)
+      shift
+      break ;;
+    *)
+      echo "error parsing args"
+      exit 1 ;;
+  esac
+done
+
+# make sure there is no `null` value returned by `yq`
+# in case the attribute could not be found
+for FIELD in host port database
+do
+  if [[ "${_map[$FIELD]}" == "null" ]]
+  then
+    if [ -t 1 ]
+    then
+      >&2 echo -e "$(tput setaf 1)$NAME.$FIELD must not be 'null'$(tput sgr0)"
+    else
+      >&2 echo -e "$NAME.$FIELD must not be 'null'"
+    fi
+    exit 1
+  fi
+done
+
+mongo --quiet "mongodb://${_map[host]}:${_map[port]}/${_map[database]}"
